import "./globals.scss";
import Footer from "./components/Footer";
import Header from "./components/Header";
import styles from "./layout.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he">
      <body>
        <Header />
        <main className={styles.mainContainer}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
