import "./globals.scss";
import Footer from "./components/Footer";
import Header from "./components/Header";
import styles from "./layout.module.scss";
import SessionProvider from '../app/components/AuthPopup/SessionProvider';
import { auth } from "@/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="he">
      <body>
        <SessionProvider session={session}>
          <Header />
          <main className={styles.mainContainer}>{children}</main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
